CREATE TABLE PURCHASE_DETAIL (
	ID_DETAIL 		INT identity(0,1) NOT NULL PRIMARY KEY,
	ID_PURCHASE		INT NOT NULL FOREIGN KEY REFERENCES PURCHASE(ID),
	STORE			VARCHAR(20) NOT NULL,
	ID_PRODUCT		INT NOT NULL,
	TITLE			VARCHAR(500) NOT NULL,
	UNIT_PRICE		DECIMAL NOT NULL,
	QUANTITY		INT NOT NULL,
	TOTAL_PRODUCT	DECIMAL NOT NULL
);